apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/pgdata"
