apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-configurer-claim0
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/prometheus-configurer-claim0"
