apiVersion: v1
kind: PersistentVolume
metadata:
  name: nmsdb
  labels:
    type: local
spec:  
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/nmsdb"
