apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata
  labels:
    type: local
spec:  
  capacity:
    storage: 100Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pgdata
    namespace: default       
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/node01/pgdata"
