apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
      - env:
        - name: CONTROLLER_HOSTNAME
          value: controller.orc8r.int
        - name: HTTP_PROXY_DOCKER_HOSTNAME
          value: docker.io
        - name: HTTP_PROXY_GITHUB_HOSTNAME
          value: github.com
        - name: PROXY_BACKENDS
          value: controller
        - name: TEST_MODE
          value: "1"
        image: docker.pkg.github.com/eduardoefb/magma_orc8r/proxy:v1.1.0-master
        imagePullPolicy: ""
        name: proxy
        ports:
        - containerPort: 9443
        - containerPort: 9444
        resources: {}
        volumeMounts:
        - mountPath: /var/opt/magma/certs
          name: certs
          readOnly: true 
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: orc8r-certs
      imagePullSecrets:
      - name: regcred
status: {}
